/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PagePanels;

import ImportantFunctions.ATM_System;
import ImportantFunctions.userInfo;
import ImportantFunctions.userTransactions;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author JA Landoy
 */
public class CheckBalance extends javax.swing.JPanel {

    /**
     * @param info the info to set
     */
    public void setInfo(userInfo info) {
        this.info = info;
    }

    
    public CheckBalance() {
        setOpaque(false);
        initComponents();
        reloadPage();
        
    }
    public void reloadPage(){
        ActionListener loadBalance = (ActionEvent evt) -> {
            if(info != null){
                t = info.getTransactions();
                BalanceNum.setText("$" + info.getAccountBalance());
                TransacDate1.setText(t[0].getDate());
                TransacDate2.setText(t[1].getDate());
                TransacDate3.setText(t[2].getDate());
                
                TransacTime1.setText(t[0].getTime());
                TransacTime2.setText(t[1].getTime());
                TransacTime3.setText(t[2].getTime());
                
                moneyTrasac1.setText(t[0].getMoney());
                moneyTrasac2.setText(t[1].getMoney());
                moneyTrasac3.setText(t[2].getMoney());
                ATM_System atm = new ATM_System();
                info = atm.setUserInfo(info.getCARD_NO(), info.getPIN_CODE(), false, 0);
            }
        };
        Timer timer = new Timer(1400, loadBalance);
        timer.start();
    
    }
    public javax.swing.JLabel getBackButton() {
        return jLabel1;
    }
    private userInfo info;
    userTransactions t[];
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(0,0,0,150));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),20,20);
            }

        };
        BalanceName = new javax.swing.JLabel();
        BalanceNum = new javax.swing.JLabel();
        TransacIcon = new javax.swing.JLabel();
        TransacDate1 = new javax.swing.JLabel();
        TransacDate2 = new javax.swing.JLabel();
        TransacDate3 = new javax.swing.JLabel();
        TransacTime1 = new javax.swing.JLabel();
        moneyTrasac1 = new javax.swing.JLabel();
        moneyTrasac2 = new javax.swing.JLabel();
        moneyTrasac3 = new javax.swing.JLabel();
        TransacTime2 = new javax.swing.JLabel();
        TransacTime3 = new javax.swing.JLabel();
        Seperator = new javax.swing.JPanel();

        setForeground(new java.awt.Color(30, 30, 30));

        jLabel1.setFont(new java.awt.Font("Garet", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/left.png"))); // NOI18N
        jLabel1.setText("BACK");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setOpaque(false);

        BalanceName.setBackground(new java.awt.Color(255, 255, 255));
        BalanceName.setFont(new java.awt.Font("Garet Book", 1, 38)); // NOI18N
        BalanceName.setForeground(new java.awt.Color(255, 255, 255));
        BalanceName.setText("Balance");

        BalanceNum.setBackground(new java.awt.Color(255, 255, 255));
        BalanceNum.setFont(new java.awt.Font("Garet Book", 0, 42)); // NOI18N
        BalanceNum.setForeground(new java.awt.Color(255, 255, 255));
        BalanceNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BalanceNum.setText("Fetching");

        TransacIcon.setBackground(new java.awt.Color(255, 255, 255));
        TransacIcon.setFont(new java.awt.Font("Garet Book", 0, 35)); // NOI18N
        TransacIcon.setForeground(new java.awt.Color(255, 255, 255));
        TransacIcon.setText("Transaction:");

        TransacDate1.setFont(new java.awt.Font("Garet Book", 0, 34)); // NOI18N
        TransacDate1.setForeground(new java.awt.Color(255, 255, 255));
        TransacDate1.setText("Fetching");

        TransacDate2.setFont(new java.awt.Font("Garet Book", 0, 34)); // NOI18N
        TransacDate2.setForeground(new java.awt.Color(255, 255, 255));
        TransacDate2.setText("Fetching");

        TransacDate3.setBackground(new java.awt.Color(255, 255, 255));
        TransacDate3.setFont(new java.awt.Font("Garet Book", 0, 34)); // NOI18N
        TransacDate3.setForeground(new java.awt.Color(255, 255, 255));
        TransacDate3.setText("Fetching");

        TransacTime1.setFont(new java.awt.Font("Garet Book", 0, 11)); // NOI18N
        TransacTime1.setForeground(new java.awt.Color(89, 89, 89));
        TransacTime1.setText("Fetching");

        moneyTrasac1.setFont(new java.awt.Font("Garet Book", 0, 32)); // NOI18N
        moneyTrasac1.setForeground(new java.awt.Color(255, 255, 255));
        moneyTrasac1.setText("Fetching");

        moneyTrasac2.setFont(new java.awt.Font("Garet Book", 0, 32)); // NOI18N
        moneyTrasac2.setForeground(new java.awt.Color(255, 255, 255));
        moneyTrasac2.setText("Fetching");

        moneyTrasac3.setFont(new java.awt.Font("Garet Book", 0, 32)); // NOI18N
        moneyTrasac3.setForeground(new java.awt.Color(255, 255, 255));
        moneyTrasac3.setText("Fetching");

        TransacTime2.setFont(new java.awt.Font("Garet Book", 0, 11)); // NOI18N
        TransacTime2.setForeground(new java.awt.Color(89, 89, 89));
        TransacTime2.setText("Fetching");

        TransacTime3.setFont(new java.awt.Font("Garet Book", 0, 11)); // NOI18N
        TransacTime3.setForeground(new java.awt.Color(89, 89, 89));
        TransacTime3.setText("Fetching");

        Seperator.setBackground(new java.awt.Color(255, 255, 255));
        Seperator.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout SeperatorLayout = new javax.swing.GroupLayout(Seperator);
        Seperator.setLayout(SeperatorLayout);
        SeperatorLayout.setHorizontalGroup(
            SeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SeperatorLayout.setVerticalGroup(
            SeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransacDate1)
                    .addComponent(TransacDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransacDate3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TransacTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransacTime3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TransacTime2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyTrasac2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moneyTrasac1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moneyTrasac3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Seperator, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(BalanceName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BalanceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TransacIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TransacIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TransacDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransacTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TransacDate2)
                                .addGap(11, 11, 11)
                                .addComponent(TransacDate3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TransacTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TransacTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(moneyTrasac1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moneyTrasac2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moneyTrasac3)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceName;
    private javax.swing.JLabel BalanceNum;
    private javax.swing.JPanel Seperator;
    private javax.swing.JLabel TransacDate1;
    private javax.swing.JLabel TransacDate2;
    private javax.swing.JLabel TransacDate3;
    private javax.swing.JLabel TransacIcon;
    private javax.swing.JLabel TransacTime1;
    private javax.swing.JLabel TransacTime2;
    private javax.swing.JLabel TransacTime3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moneyTrasac1;
    private javax.swing.JLabel moneyTrasac2;
    private javax.swing.JLabel moneyTrasac3;
    // End of variables declaration//GEN-END:variables
}
