/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PagePanels;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author JA Landoy
 */
public class CheckBalance extends javax.swing.JPanel {

    /**
     * Creates new form CheckBalance
     */
    public CheckBalance() {
        setOpaque(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                Graphics2D g2 = (Graphics2D)g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(0,0,0,190));
                g2.fillRoundRect(0,0,getWidth(),getHeight(),20,20);
            }

        };
        BalanceName = new javax.swing.JLabel();
        BalanceNum = new javax.swing.JLabel();
        TransacIcon = new javax.swing.JLabel();
        TransacDate1 = new javax.swing.JLabel();
        TransacDate2 = new javax.swing.JLabel();
        TransacDate3 = new javax.swing.JLabel();
        TransacTime1 = new javax.swing.JLabel();
        moneyTrasac1 = new javax.swing.JLabel();
        moneyTrasac2 = new javax.swing.JLabel();
        moneyTrasac3 = new javax.swing.JLabel();
        TransacTime2 = new javax.swing.JLabel();
        TransacTime3 = new javax.swing.JLabel();
        Seperator = new javax.swing.JPanel();

        setForeground(new java.awt.Color(30, 30, 30));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setOpaque(false);

        BalanceName.setBackground(new java.awt.Color(255, 255, 255));
        BalanceName.setFont(new java.awt.Font("Garet Book", 1, 38)); // NOI18N
        BalanceName.setForeground(new java.awt.Color(255, 255, 255));
        BalanceName.setText("Balance");

        BalanceNum.setBackground(new java.awt.Color(255, 255, 255));
        BalanceNum.setFont(new java.awt.Font("Garet Book", 0, 42)); // NOI18N
        BalanceNum.setForeground(new java.awt.Color(255, 255, 255));
        BalanceNum.setText("$100,00");

        TransacIcon.setBackground(new java.awt.Color(255, 255, 255));
        TransacIcon.setFont(new java.awt.Font("Garet Book", 0, 35)); // NOI18N
        TransacIcon.setForeground(new java.awt.Color(255, 255, 255));
        TransacIcon.setText("Transaction:");

        TransacDate1.setFont(new java.awt.Font("Garet Book", 0, 34)); // NOI18N
        TransacDate1.setForeground(new java.awt.Color(255, 255, 255));
        TransacDate1.setText("Aug. 5, 2025");

        TransacDate2.setFont(new java.awt.Font("Garet Book", 0, 34)); // NOI18N
        TransacDate2.setForeground(new java.awt.Color(255, 255, 255));
        TransacDate2.setText("July 36, 2025");

        TransacDate3.setBackground(new java.awt.Color(255, 255, 255));
        TransacDate3.setFont(new java.awt.Font("Garet Book", 0, 34)); // NOI18N
        TransacDate3.setForeground(new java.awt.Color(255, 255, 255));
        TransacDate3.setText("July 36, 2025");

        TransacTime1.setFont(new java.awt.Font("Garet Book", 0, 11)); // NOI18N
        TransacTime1.setForeground(new java.awt.Color(89, 89, 89));
        TransacTime1.setText("13:30");

        moneyTrasac1.setFont(new java.awt.Font("Garet Book", 0, 32)); // NOI18N
        moneyTrasac1.setForeground(new java.awt.Color(255, 255, 255));
        moneyTrasac1.setText("+ $50,000");

        moneyTrasac2.setFont(new java.awt.Font("Garet Book", 0, 32)); // NOI18N
        moneyTrasac2.setForeground(new java.awt.Color(255, 255, 255));
        moneyTrasac2.setText("+ $500");

        moneyTrasac3.setFont(new java.awt.Font("Garet Book", 0, 32)); // NOI18N
        moneyTrasac3.setForeground(new java.awt.Color(255, 255, 255));
        moneyTrasac3.setText("- $3,000");

        TransacTime2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TransacTime2.setForeground(new java.awt.Color(89, 89, 89));
        TransacTime2.setText("21:30");

        TransacTime3.setFont(new java.awt.Font("Garet Book", 0, 11)); // NOI18N
        TransacTime3.setForeground(new java.awt.Color(89, 89, 89));
        TransacTime3.setText("17:30");

        Seperator.setBackground(new java.awt.Color(255, 255, 255));
        Seperator.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout SeperatorLayout = new javax.swing.GroupLayout(Seperator);
        Seperator.setLayout(SeperatorLayout);
        SeperatorLayout.setHorizontalGroup(
            SeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SeperatorLayout.setVerticalGroup(
            SeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransacDate1)
                    .addComponent(TransacDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransacDate3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TransacTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransacTime3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TransacTime2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyTrasac2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moneyTrasac1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moneyTrasac3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Seperator, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TransacIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(BalanceName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BalanceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TransacIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TransacDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransacTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TransacDate2)
                                .addGap(11, 11, 11)
                                .addComponent(TransacDate3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TransacTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TransacTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(moneyTrasac1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moneyTrasac2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moneyTrasac3)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceName;
    private javax.swing.JLabel BalanceNum;
    private javax.swing.JPanel Seperator;
    private javax.swing.JLabel TransacDate1;
    private javax.swing.JLabel TransacDate2;
    private javax.swing.JLabel TransacDate3;
    private javax.swing.JLabel TransacIcon;
    private javax.swing.JLabel TransacTime1;
    private javax.swing.JLabel TransacTime2;
    private javax.swing.JLabel TransacTime3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moneyTrasac1;
    private javax.swing.JLabel moneyTrasac2;
    private javax.swing.JLabel moneyTrasac3;
    // End of variables declaration//GEN-END:variables
}
