/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PagePanels;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author Margaret Anne Lasay
 */
public class Deposit extends javax.swing.JPanel {

    javax.swing.Timer timer;
    ActionListener taskPerformer;
    
    public boolean isNotNumpad;
    public Deposit() {
        setOpaque(false);
        initComponents();
        taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                background1.addFocusListener(new FocusListener() {
                @Override
                public void focusGained(FocusEvent e) {
                    isNotNumpad = true;    
                    numpadContainer1.clearInput();
                }

                @Override
                public void focusLost(FocusEvent e) {
                    isNotNumpad = false;
                }
                
             });
                if(!numpadContainer1.getInput().isEmpty()&&!isNotNumpad){
                
                    depositamm.setText(numpadContainer1.getInput());
                }

                
                
                SwingUtilities.updateComponentTreeUI(depositamm);
                
                
            }
        };
        
        timer = new javax.swing.Timer(20, taskPerformer);
        timer.start();
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numpadContainer1 = new components.numpadContainer();
        jLabel1 = new javax.swing.JLabel();
        background1 = new components.background(){
            @Override
            public void paintComponent(Graphics g) {

                g.setColor(new Color(0,0,0,70));
                g.fillRoundRect(0, 0, getWidth(), getHeight(), 50, 50);

            }

        };
        jSeparator1 = new javax.swing.JSeparator();
        onehando = new components.ValueButton();
        onetao = new components.ValueButton();
        fivehando = new components.ValueButton();
        totao = new components.ValueButton();
        fortao = new components.ValueButton();
        faitao = new components.ValueButton();
        tentao = new components.ValueButton();
        printrec = new javax.swing.JCheckBox();
        depositamm = new javax.swing.JLabel();
        balamm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0, 0));
        setForeground(new Color(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1048, 562));

        jLabel1.setFont(new java.awt.Font("Garet Book", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cash Deposit");

        background1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background1.setPreferredSize(new java.awt.Dimension(566, 309));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        onehando.setFont(new java.awt.Font("Garet", 1, 14));
        onehando.setForeground(new java.awt.Color(255,255,255));
        onehando.setText("100");
        onehando.setFont(new java.awt.Font("Garet Book", 0, 12)); // NOI18N
        onehando.setPreferredSize(new java.awt.Dimension(130, 30));
        onehando.setRadius(30);
        onehando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onehandoActionPerformed(evt);
            }
        });

        fivehando1.setFont(new java.awt.Font("Garet", 1, 14));
        fivehando1.setForeground(new java.awt.Color(255,255,255));
        onetao.setText("1000");
        onetao.setFont(new java.awt.Font("Garet Book", 0, 12)); // NOI18N
        onetao.setPreferredSize(new java.awt.Dimension(130, 30));
        onetao.setRadius(30);
        onetao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onetaoActionPerformed(evt);
            }
        });

        fivehando1.setFont(new java.awt.Font("Garet", 1, 14));
        fivehando1.setForeground(new java.awt.Color(255,255,255));
        fivehando.setText("500");
        fivehando.setFont(new java.awt.Font("Garet Book", 0, 12)); // NOI18N
        fivehando.setPreferredSize(new java.awt.Dimension(130, 30));
        fivehando.setRadius(30);
        fivehando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivehandoActionPerformed(evt);
            }
        });

        fivehando1.setFont(new java.awt.Font("Garet", 1, 14));
        fivehando1.setForeground(new java.awt.Color(255,255,255));
        totao.setText("2000");
        totao.setFont(new java.awt.Font("Garet Book", 0, 12)); // NOI18N
        totao.setPreferredSize(new java.awt.Dimension(160, 30));
        totao.setRadius(30);
        totao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaoActionPerformed(evt);
            }
        });

        fivehando1.setFont(new java.awt.Font("Garet", 1, 14));
        fivehando1.setForeground(new java.awt.Color(255,255,255));
        fortao.setText("4000");
        fortao.setFont(new java.awt.Font("Garet Book", 0, 12)); // NOI18N
        fortao.setPreferredSize(new java.awt.Dimension(160, 30));
        fortao.setRadius(30);
        fortao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fortaoActionPerformed(evt);
            }
        });

        fivehando1.setFont(new java.awt.Font("Garet", 1, 14));
        fivehando1.setForeground(new java.awt.Color(255,255,255));
        faitao.setText("5000");
        faitao.setFont(new java.awt.Font("Garet Book", 0, 12)); // NOI18N
        faitao.setPreferredSize(new java.awt.Dimension(160, 30));
        faitao.setRadius(30);
        faitao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faitaoActionPerformed(evt);
            }
        });

        fivehando1.setFont(new java.awt.Font("Garet", 1, 14));
        fivehando1.setForeground(new java.awt.Color(255,255,255));
        tentao.setText("10000");
        tentao.setFont(new java.awt.Font("Garet Book", 0, 12)); // NOI18N
        tentao.setPreferredSize(new java.awt.Dimension(160, 30));
        tentao.setRadius(30);
        tentao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentaoActionPerformed(evt);
            }
        });

        printrec.setFont(new java.awt.Font("Garet Book", 0, 12)); // NOI18N
        printrec.setText("Print Reciept");
        printrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printrecActionPerformed(evt);
            }
        });

        depositamm.setFont(new java.awt.Font("Garet Book", 0, 36)); // NOI18N

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printrec)
                .addGap(26, 26, 26))
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(onehando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(fivehando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(onetao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(faitao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fortao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tentao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(depositamm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositamm, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onehando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onetao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fivehando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fortao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faitao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tentao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(printrec)
                .addGap(23, 23, 23))
        );

        balamm.setFont(new java.awt.Font("Garet Book", 0, 36)); // NOI18N
        balamm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balamm.setText("50,000,000,000,000.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numpadContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balamm, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balamm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numpadContainer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(background1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void totaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaoActionPerformed
        // TODO add your handling code here:
        depositamm.setText("2000");
    }//GEN-LAST:event_totaoActionPerformed

    private void faitaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faitaoActionPerformed
        // TODO add your handling code here:
        depositamm.setText("5000");
    }//GEN-LAST:event_faitaoActionPerformed

    private void fivehandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivehandoActionPerformed
        // TODO add your handling code here:
        depositamm.setText("500");
    }//GEN-LAST:event_fivehandoActionPerformed

    private void onetaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onetaoActionPerformed
        // TODO add your handling code here:
        depositamm.setText("1000");
    }//GEN-LAST:event_onetaoActionPerformed

    private void fortaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fortaoActionPerformed
        // TODO add your handling code here:
        depositamm.setText("4000");
    }//GEN-LAST:event_fortaoActionPerformed

    private void tentaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentaoActionPerformed
        // TODO add your handling code here:
        depositamm.setText("10000");
    }//GEN-LAST:event_tentaoActionPerformed

    private void printrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printrecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printrecActionPerformed

    private void onehandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onehandoActionPerformed
        // TODO add your handling code here:
        depositamm.setText("100");
    }//GEN-LAST:event_onehandoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.background background1;
    private javax.swing.JLabel balamm;
    private javax.swing.JLabel depositamm;
    private components.ValueButton faitao;
    private components.ValueButton fivehando;
    private components.ValueButton fortao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private components.numpadContainer numpadContainer1;
    private components.ValueButton onehando;
    private components.ValueButton onetao;
    private javax.swing.JCheckBox printrec;
    private components.ValueButton tentao;
    private components.ValueButton totao;
    // End of variables declaration//GEN-END:variables

    private static class fivehando1 {

        private static void setFont(Font font) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static void setForeground(Color color) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public fivehando1() {
        }
    }
}
