/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PagePanels;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author JA Landoy
 */
public class Reciept extends javax.swing.JPanel {

    /**
     * Creates new form Reciept
     */
    public Reciept() {
         setOpaque(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(255, 255, 255, 153));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
            }

        };
        NameSym = new javax.swing.JLabel();
        logo1 = new components.logo();
        AccountNO = new javax.swing.JLabel();
        Balance = new javax.swing.JLabel();
        Deposit = new javax.swing.JLabel();
        Withdrew = new javax.swing.JLabel();
        nameName = new javax.swing.JLabel();
        AccNum = new javax.swing.JLabel();
        BalNum = new javax.swing.JLabel();
        DepositNum = new javax.swing.JLabel();
        WithdrewNum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Remaining = new javax.swing.JLabel();
        RemainingNum = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        NameSym.setFont(new java.awt.Font("Garet Book", 0, 22)); // NOI18N
        NameSym.setForeground(new java.awt.Color(0, 0, 0));
        NameSym.setText("Name:");

        logo1.setMaximumSize(new java.awt.Dimension(152, 100));
        logo1.setMinimumSize(new java.awt.Dimension(152, 100));

        AccountNO.setFont(new java.awt.Font("Garet Book", 0, 22)); // NOI18N
        AccountNO.setForeground(new java.awt.Color(0, 0, 0));
        AccountNO.setText("Account No.:");

        Balance.setFont(new java.awt.Font("Garet Book", 0, 22)); // NOI18N
        Balance.setForeground(new java.awt.Color(0, 0, 0));
        Balance.setText("Balance:");

        Deposit.setFont(new java.awt.Font("Garet Book", 0, 22)); // NOI18N
        Deposit.setForeground(new java.awt.Color(0, 0, 0));
        Deposit.setText("Deposited:");

        Withdrew.setFont(new java.awt.Font("Garet Book", 0, 22)); // NOI18N
        Withdrew.setForeground(new java.awt.Color(0, 0, 0));
        Withdrew.setText("Withdrew:");

        nameName.setFont(new java.awt.Font("Garet Book", 0, 26)); // NOI18N
        nameName.setForeground(new java.awt.Color(0, 0, 0));
        nameName.setText("Maranguis, Jeriana P. ");

        AccNum.setFont(new java.awt.Font("Garet Book", 0, 21)); // NOI18N
        AccNum.setForeground(new java.awt.Color(0, 0, 0));
        AccNum.setText("111111111111");

        BalNum.setFont(new java.awt.Font("Garet Book", 0, 21)); // NOI18N
        BalNum.setForeground(new java.awt.Color(0, 0, 0));
        BalNum.setText("$ 50, 000");

        DepositNum.setFont(new java.awt.Font("Garet Book", 0, 21)); // NOI18N
        DepositNum.setForeground(new java.awt.Color(0, 0, 0));
        DepositNum.setText("+ $500");

        WithdrewNum.setFont(new java.awt.Font("Garet Book", 0, 21)); // NOI18N
        WithdrewNum.setForeground(new java.awt.Color(0, 0, 0));
        WithdrewNum.setText("-$3,000");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        Remaining.setFont(new java.awt.Font("Garet Book", 0, 23)); // NOI18N
        Remaining.setForeground(new java.awt.Color(0, 0, 0));
        Remaining.setText("Remaining:");

        RemainingNum.setFont(new java.awt.Font("Garet Book", 0, 25)); // NOI18N
        RemainingNum.setForeground(new java.awt.Color(0, 0, 0));
        RemainingNum.setText("$45,000");

        Date.setFont(new java.awt.Font("Garet Book", 0, 13)); // NOI18N
        Date.setForeground(new java.awt.Color(0, 0, 0));
        Date.setText("July 36,2025 ");

        Time.setFont(new java.awt.Font("Garet Book", 0, 13)); // NOI18N
        Time.setForeground(new java.awt.Color(0, 0, 0));
        Time.setText("20:30");

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NameSym)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(nameName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Deposit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Withdrew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WithdrewNum))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DepositNum))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AccountNO, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AccNum))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Balance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BalNum))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Remaining)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RemainingNum))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Date)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Time)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameSym)
                    .addComponent(nameName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountNO)
                    .addComponent(AccNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Balance, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BalNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deposit)
                    .addComponent(DepositNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Withdrew)
                    .addComponent(WithdrewNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Remaining)
                    .addComponent(RemainingNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Time)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNum;
    private javax.swing.JLabel AccountNO;
    private javax.swing.JLabel BalNum;
    private javax.swing.JLabel Balance;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Deposit;
    private javax.swing.JLabel DepositNum;
    private javax.swing.JLabel NameSym;
    private javax.swing.JLabel Remaining;
    private javax.swing.JLabel RemainingNum;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Withdrew;
    private javax.swing.JLabel WithdrewNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private components.logo logo1;
    private javax.swing.JLabel nameName;
    // End of variables declaration//GEN-END:variables
}
