/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author quasar
 */
public class numpad extends javax.swing.JPanel {

    /**
     * Creates new form numpad
     */
    String textString = "";
    public numpadButton[] numButton = new numpadButton[12];
    String numpadLabel[] = {"1","2","3","4","5","6","7","8","9","CLR", "0", "<"};
    public numpad() {
        setOpaque(false);
        initComponents();
        initializeTilePanels();
    }
    private void initializeTilePanels() {
        
        
        this.setLayout(new GridLayout(4, 3, 5, 5)); 

        for (int i = 0; i < 12; i++) {
            final int tileIndex = i; 
                numButton[i] = new numpadButton();
                numButton[i].setButtonLabel(numpadLabel[i]);
                numButton[i].addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent evt) {
                    if (SwingUtilities.isLeftMouseButton(evt)) {
                        System.out.println(numButton[tileIndex].getLabelText());
                        if(numButton[tileIndex].getLabelText().equals("CLR")){
                            textString = "";
                        
                        } else if(numButton[tileIndex].getLabelText().equals("<")){
                            if(textString.length() == 0){
                                textString = "";
                            } else {
                                textString = textString.substring(0, textString.length() - 1);
                            }
                        } else {
                            if(textString.length() < 16){
                                textString = textString.concat(numpadLabel[tileIndex]);
                            }
                        }
                        System.out.println("Text:" + textString);
                            
                        
                        
                    }
                }
            });
            this.add(numButton[i]); 
        }
    }
    public String returnInputString(){
        return textString;
    
    }
    public void clearString(){
        this.textString = "";
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
