/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package buttons;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;

import javax.swing.SwingUtilities;

/**
 *
 * @author quasar
 */
public class LanguageButton extends javax.swing.JPanel {

    /**
     * Creates new form LanguageButton
     */
    String languages[] = {"English", "Filipino"};
    String iconLocation[] = {"/resource/united-kingdom.png","/resource/philippines.png"};
    int currentLanguage = 0;
    int secondOption = 1;
    
    
    
    public LanguageButton() {
        setOpaque(false);
        setBackground(new Color(0,0,0,0));
        initComponents();
        
        
        
    }
    public String getLanguage(){
        return languages[currentLanguage];
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void background1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background1MouseEntered
        // TODO add your handling code here:
        
        background2.setVisible(true);   
        firstButtonOnFocus = true;
    }//GEN-LAST:event_background1MouseEntered

    private void background2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background2MouseEntered
        // TODO add your handling code here:
        secondButtonOnFocus = true;
    }//GEN-LAST:event_background2MouseEntered

    private void background1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background1MouseExited
        // TODO add your handling code here:
        firstButtonOnFocus = false;
    }//GEN-LAST:event_background1MouseExited

    private void background2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background2MouseExited
        // TODO add your handling code here:
        secondButtonOnFocus = false;
    }//GEN-LAST:event_background2MouseExited
    
    public void setSecondButtonInvisible(){
        background2.setVisible(false);
    }
    public boolean noMouseActivity(){
        if(firstButtonOnFocus == true || secondButtonOnFocus == true){
            return false;
        } else {
            return true;
        }
        
    }
    public boolean secondButtonOnFocus;
    public boolean firstButtonOnFocus;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
